### ISSUE TITLE
sample 里面写错了    app:actionViewClass="com.gihub.leonardoxh.fakesearchview.FakeSearchView"

### ISSUE THREAD

**Issue by beiliubei** [leonardoxh/FakeSearchView#1]
sample 里面写错了    app:actionViewClass="com.gihub.leonardoxh.fakesearchview.FakeSearchView"

=> 

 app:actionViewClass="com.github.leonardoxh.fakesearchview.FakeSearchView"

**Comment by leonardoxh** [comment]
Ops.. I'll change this thanks

**Comment by leonardoxh** [comment]
It's OK now
